# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0007_auto_20170911_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='img',
            field=models.ImageField(blank=True, default='/static/img_schedule/sched.png', upload_to='site1/static/img_schedule'),
        ),
    ]
